### ISSUE TITLE
[优化] 优化找不到 rt.jar 时给用户的提示信息

### ISSUE THREAD

**Issue by He1za1** [jar-analyzer/jar-analyzer#107]
## 描述 | DESC

请描述你遇到的 BUG
无法找到jre环境且不能自定义
![image](https://github.com/user-attachments/assets/7ef3c100-880f-4375-9302-4b08333af8ca)

## 复现 | REPRODUCE

是否可以给出复现该 BUG 的步骤

## 截图 | SCREENSHOT

是否可以提供截图

## 环境 | ENV

环境信息
- 你的操作系统
- 你使用的 `jar-analyzer` 版本
- 你使用的哪一种 `release` 类型

**Comment by 4ra1n** [comment]
@He1za1 默认从 JAVA_HOME 里找，如果非 JAVA 8 一半找不到 rt.jar 变成了其他格式

建议是使用 windows-full 版本应该是可以顺利找到

**Comment by 4ra1n** [comment]
已给出提示

![image](https://github.com/user-attachments/assets/ffe830ee-e8c0-4666-a79f-c82af9d4b26e)

**Comment by He1za1** [comment]
![image](https://github.com/user-attachments/assets/fba71a25-bc51-4a63-a247-50cffab94006)
老哥，是不是只能识别到c盘，其他盘符不行

**Comment by 4ra1n** [comment]
代码是从环境变量java.home里取的，不是盘符的问题

**Comment by 4ra1n** [comment]
System.getProperty("java.home"); 和环境遍历的 java_home 不一定是一个东西

前者应该是实际启动这个 JAVA 程序的 java 版本，未必是 java_home

**Comment by 4ra1n** [comment]
@He1za1 参考图片，这两个不是一个 java_home

![image](https://github.com/user-attachments/assets/72739781-3e83-41c5-bcbd-0bee29bbe6e2)

你可以 java -jar 启动的时候 这个 java 用绝对路径：D:\Java\xxx\bin\java.exe -jar 

最简单的办法还是你用 windows-full 版本

**Comment by 4ra1n** [comment]
4.0
