### ISSUE TITLE
[BUG] 搜索功能勾选 binary search 开始搜索会一直弹窗

### ISSUE THREAD

**Issue by XinCaoZ** [jar-analyzer/jar-analyzer#119]
## 描述 | DESC

当我在搜索处勾选了binary search和like search时，输入要搜索的数据点击开始搜索会不间断的弹出提示框

## 复现 | REPRODUCE

勾选上述两个选项，String输入框中输入任意值，点击开始搜索

## 截图 | SCREENSHOT

<img width="1239" alt="image" src="https://github.com/user-attachments/assets/cc56ba13-b8c8-45df-b489-a4bdc18c7c63">
<img width="1255" alt="image" src="https://github.com/user-attachments/assets/fb636760-dd28-4508-b883-c9d7bc6d096b">

## 环境 | ENV

环境信息
- macOS 15.0
- jar-analyzer-4.0.zip
- 本地java环境 1.8.0_391

**Comment by 4ra1n** [comment]
@XinCaoZ 

感谢反馈

binary search 我没有测试过太多，因为不怎么用，我之后处理下

目前就你的需求来看，搜索 `ls` 可以考虑字符串包含搜索，该功能稳定可用

**Comment by 4ra1n** [comment]
4.1
