### ISSUE TITLE
[优化] 内存马扫描功能优化启动参数提示

### ISSUE THREAD

**Issue by hi-unc1e** [jar-analyzer/jar-analyzer#124]
今天测了下内存马扫描的功能。
感受是： 建议优化一下启动参数的说明，就是这个界面的说明
![image](https://github.com/user-attachments/assets/d4cd558d-f701-4606-8642-754db358a148)

对了不知道是否支持TongWeb等中间件（我看了下代码，没找到对应的业务函数），提示语先放在这里了。
自己测了一下 tongweb，端口监听后，也没连上。

对于 TongWeb 等其他中间件，您可以修改startserver.sh， 参考以下命令：
- 这里建议用引号包裹javaagent选项的value
- 修改`startserver.sh`
```bash
TW_OPTS="${TW_OPTS} -javaagent:\"/root/TongWeb7.0/bin/agent.jar=port=10033;password=P4sSW0rD\" "  
```

![image](https://github.com/user-attachments/assets/585b1d78-699b-4b9e-bf54-f51f3df6bcd4)

![image](https://github.com/user-attachments/assets/30fe33c7-929e-4c84-b7f5-8fcc4792f7c3)

**Comment by 4ra1n** [comment]
感谢反馈

TongWeb 目前不支持，只测试过 Tomcat

启动参数提示这里，我之后考虑优化下

**Comment by 4ra1n** [comment]
我看了下代码，目前的 agent 只支持 tomcat

对于其他中间件，可以使用 https://github.com/4ra1n/shell-analyzer 项目，理论上可以支持

jar-analzyer 和 shell-analyzer 项目的代码不一样
