### ISSUE TITLE
[FEAT] 后续版本支持类似 IDEA 展示的 TAB 标签页

### ISSUE THREAD

**Issue by try-to-change** [jar-analyzer/jar-analyzer#127]
## 描述 | DESC
类似idea这种，
![image](https://github.com/user-attachments/assets/f33ee200-3aff-4df0-ac04-d3d1501907ba)

**Comment by 4ra1n** [comment]
好的，我之后尝试下

**Comment by try-to-change** [comment]
> 这个功能有替代选项：
> 
> * 查看 history 列表，包含了你历史打开的每一个方法
> * 使用 前进 和 后退 按钮，可以做到类似 tab 的效果

好的，谢谢，我试试，就是tab页面在看多个类时候可能会一目了然自己看过那些来回切换
