### ISSUE TITLE
希望 Sping Controller 也可以像Spring Mappings一样有路径信息

### ISSUE THREAD

**Issue by veo** [jar-analyzer/jar-analyzer#19]
Spring Mappings 可以显示路径非常方便，但是他不是完整的路径。当需要去找某个链接对应的函数时，还是需要一个一个点开去确认完整路径

![sping](https://github.com/jar-analyzer/jar-analyzer/assets/38176360/564769bf-6d8f-434e-b566-577c350c61a6)

**Comment by 4ra1n** [comment]
感谢反馈，之后我看下

**Comment by 4ra1n** [comment]
2.10
