### ISSUE TITLE
在选择目录批量分析jar包的时候卡住了

### ISSUE THREAD

**Issue by Le1a** [jar-analyzer/jar-analyzer#2]
很快就完成了数据库创建，但是此后的很长一段时间都没有任何进展，引擎状态也是关闭
![image](https://github.com/jar-analyzer/jar-analyzer/assets/97610822/6891d62c-565a-41de-9f54-8d692459da9a)

**Comment by 4ra1n** [comment]
14 万个 Jar 唉，实在是太大了~

**Comment by Le1a** [comment]
工具没有问题，是我内存太小了，这就去加64G内存条
![65b9bf0f6eb3f0c6aabd1c17e145d616](https://github.com/jar-analyzer/jar-analyzer/assets/97610822/aa3a915f-850f-4ebe-920a-58cb9f8a2552)

**Comment by l0n3rs** [comment]
> 工具没有问题，是我内存太小了，这就去加64G内存条 ![65b9bf0f6eb3f0c6aabd1c17e145d616](https://user-images.githubusercontent.com/97610822/277570733-aa3a915f-850f-4ebe-920a-58cb9f8a2552.jpg)

别卷了，我3000多个jar跑了一夜
