### ISSUE TITLE
[BUG] 打开一个新的 jar 包之后，左侧目录未清空

### ISSUE THREAD

**Issue by gausszhou** [jar-analyzer/jar-analyzer#21]
[BUG] 打开一个新的 jar 包之后，左侧目录未清空，如图所示
![image](https://github.com/jar-analyzer/jar-analyzer/assets/46297500/ea953fd8-4a9f-456e-a78e-0adf96fe9a0b)

**Comment by 4ra1n** [comment]
好的，感谢反馈，我看一下

**Comment by 4ra1n** [comment]
尝试 2.12 版本，如果有问题可以再反馈
