### ISSUE TITLE
高分辨率情况下 GUI 界面较小

### ISSUE THREAD

**Issue by boyi0508** [jar-analyzer/jar-analyzer#22]
win11中启动后gui界面显示很小，非正常显示。

**Comment by 4ra1n** [comment]
本项目主要针对 1080P 分辨率处理，考虑到这个分辨率是大多数人使用的，如果你是 4K 屏幕可能确实会比较小，没有针对性地处理，这个之后会想办法看下

**Comment by 4ra1n** [comment]
2.15 已支持全屏

**Comment by fc8** [comment]
> 2.15 已支持全屏

![Snipaste_2024-07-17_17-10-30](https://github.com/user-attachments/assets/a1aa3b58-38fd-4c93-918e-285c52eb45d5)
全屏组件并不会变大，还是很小，是不是可以设置按钮菜单等自适应分辨率宽高。

**Comment by 4ra1n** [comment]
临时解决是：

尝试 -> 设置 -> 系统 -> 屏幕 -> 缩放

![image](https://github.com/user-attachments/assets/e4a7982b-5c19-483c-a859-d52349cfd289)

可以修改 UI 的大小

JAVA SWING 的 GUI 可能没有那么动态，不太好自适应分辨率，我之后有空研究看看

**Comment by fauns-o** [comment]
3.1K 的分辨率
![image](https://github.com/user-attachments/assets/1c481b98-469c-48e5-806c-813cc7430786)
