### ISSUE TITLE
[BUG] RASP 会拦截正常的功能（虽然只是测试功能）

### ISSUE THREAD

**Issue by ViCrack** [jar-analyzer/jar-analyzer#23]
提个bug，偶然看了一下，这个rasp的功能会把自己功能给拦截了。。。

另外话说这块的反序列化还有更简单的实现，只重载writeClassDescriptor不全面的

![图片](https://github.com/jar-analyzer/jar-analyzer/assets/18179821/d8178865-ce47-4f2f-b21a-e9f13bed3005)

**Comment by 4ra1n** [comment]
2.14 更新已处理
