### ISSUE TITLE
启动时输出的 logo 少了个 z？

### ISSUE THREAD

**Issue by xishir** [jar-analyzer/jar-analyzer#24]
<img width="559" alt="image" src="https://github.com/jar-analyzer/jar-analyzer/assets/21237603/d5f5d2b9-f055-4249-9405-fcdb4a187876">

analyzer->analyer

**Comment by 4ra1n** [comment]
我擦，确实啊，我处理下哈哈哈哈

**Comment by 4ra1n** [comment]
2.15
