### ISSUE TITLE
thinkpad window10 程序尺寸问题

### ISSUE THREAD

**Issue by YYHYlh** [jar-analyzer/jar-analyzer#3]
![image](https://github.com/jar-analyzer/jar-analyzer/assets/28374935/ee0a6065-8089-4a91-9114-59a01daaba44)
右边边框无法调整。使用的是https://jar-analyzer-2.0-beta-windows-embed.zip

**Comment by 4ra1n** [comment]
UI 适配的是 Windows 1080P 无缩放的情况，现在显示屏应该都是 1080P 起步，可能你需要调节下缩放

如图，1080P 调到 100% 是正常的

![image](https://github.com/jar-analyzer/jar-analyzer/assets/34726933/3129a535-7b69-4dc4-a23c-40e4b1760371)
