### ISSUE TITLE
导入lib包，能否导入只包含指定字段包名的jar

### ISSUE THREAD

**Issue by KANAZAWA1** [jar-analyzer/jar-analyzer#31]
师傅，我有一个web的代码，我想导入他的lib包到jar-analyzer工具中，但是他会把lib包里所有的jar导入，我只想导入包含指定字段包名的jar进去，比如这个包名包含smartbi相关的jar导入即可,是否可行呢？
<img width="247" alt="image" src="https://github.com/user-attachments/assets/8a769b5b-5050-4989-b293-df901457e4a9">

**Comment by KANAZAWA1** [comment]
工具是否可以自行去遍历判断然后只导入相关的jar呢？

**Comment by 4ra1n** [comment]
如图，现在支持包名或类名的黑名单

你可以把不需要的包名例如 sun oracle 等加入黑名单，以减少分析的包

![image](https://github.com/user-attachments/assets/36ab2486-bef7-4108-8233-1f4e9f5e5230)

或者 smartbi 相关的 jar 文件，从名字是可以看出来的，可以自行筛选一下再加入分析

我之后看下加个分析白名单的功能

**Comment by 4ra1n** [comment]
已新增分析类和包名的白名单，2.21发布，着急用可以自己maven build下
