### ISSUE TITLE
此项目能PR吗？我增加了一个新的功能点

### ISSUE THREAD

**Issue by Gosiu** [jar-analyzer/jar-analyzer#33]
**基于2.20**
### API中的api/get_methods_by_str/str=参数
没有明确写明搜索是否按照path查找，而且源码中此功能的JSON实现，基本每次会轻松内存溢出。

因此新建此需求：
### _1.通过Mapping的Path来查找对应方法_
![image](https://github.com/user-attachments/assets/28c71885-9b32-4308-9483-aeda8709ab3d)

### _2.后续我会优化SQLITE中存储PATH的格式_

**Comment by 4ra1n** [comment]
欢迎贡献！

**Comment by Gosiu** [comment]
processed

**Comment by 4ra1n** [comment]
@Gosiu 有一点小问题，我这边看看修复下就可以

![image](https://github.com/user-attachments/assets/b2b52245-48e5-4e1e-bde6-932ec24ff2dc)

**Comment by 4ra1n** [comment]
实际上是 /get /post /req 但是记录了 /ge /pos /re

**Comment by Gosiu** [comment]
> @Gosiu 有一点小问题，我这边看看修复下就可以
> 
> ![image](https://private-user-images.githubusercontent.com/34726933/349764333-b2b52245-48e5-4e1e-bde6-932ec24ff2dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyNzE0NDcsIm5iZiI6MTcyMTI3MTE0NywicGF0aCI6Ii8zNDcyNjkzMy8zNDk3NjQzMzMtYjJiNTIyNDUtNDhlNS00ZTFlLWJkZTYtOTMyZWMyNGZmMmRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDAyNTIyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwZGEyYzkyY2FlZDdhMzJlNWNjNTU5MzQ4N2IyZmY4NDkwN2QyZWUyNmE0ZmQzNzgyNjI2MzA5N2U0OTVjODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yUzwKt793-3erXq35HlfzQKXc8I5Bv6CHsxXxEY-JYQ)

此实现在实际使用中存在内存溢出的情况，我想把spring这类操作逐步移到gui。
目前还发现了重建db时，数据不会覆盖的问题，生成时，实际数据会在表中重复

**Comment by 4ra1n** [comment]
如果当前目录存在 db 重新分析时会提示，是否要删除这个 db 文件，删除后创建新的，不删除的话，目前是新增数据不是覆盖

内存溢出的情况你可以具体给个 spring 代码例子嘛，我看看

**Comment by Gosiu** [comment]
@4ra1n 搜索path的事情，懒得找sqlite的搜索实现了，直接用的现有方法取得结果，存在性能开销，后续尽量改写成库中查找
提示，是否要删除这个 db 文件，是，实际数据还在。直接在现有库中插入了，这部分需求我可以来写？
![image](https://github.com/user-attachments/assets/e436478f-60be-42b0-9ec8-74a418440e90)
内存溢出的情况，在db量很大的时候会出现，量小不会，等会给栈信息

**Comment by 4ra1n** [comment]
感谢！你有新的修复和功能，欢迎新的 PR

**Comment by Gosiu** [comment]
@4ra1n 量小正常
![image](https://github.com/user-attachments/assets/a11193de-49a3-421d-b19c-1cfedd50e361)
量大起飞
![image](https://github.com/user-attachments/assets/3b680f1a-ef74-42a3-865d-788035b1caed)
一秒钟200MB内存。我看了实现代码，有点问题

Exception in thread "NanoHttpd Request Processor (#1)" java.lang.OutOfMemoryError: try enabling LargeObject feature instead
        at com.alibaba.fastjson2.JSONWriterUTF16.ensureCapacity(JSONWriterUTF16.java:1998)
        at com.alibaba.fastjson2.JSONWriterUTF16.writeString(JSONWriterUTF16.java:3219)
        at com.alibaba.fastjson2.writer.OWG_1_6_MethodResult.write(Unknown Source)
        at com.alibaba.fastjson2.writer.ObjectWriterImplList.write(ObjectWriterImplList.java:364)
        at com.alibaba.fastjson2.JSON.toJSONString(JSON.java:3085)
        at me.n1ar4.jar.analyzer.server.handler.GetMethodHandler.handle(GetMethodHandler.java:25)
        at me.n1ar4.jar.analyzer.server.PathMatcher.handleReq(PathMatcher.java:48)
        at me.n1ar4.jar.analyzer.server.JarAnalyzerServer.serve(JarAnalyzerServer.java:23)
        at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)
        at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
        at java.lang.Thread.run(Thread.java:750)

**Comment by Gosiu** [comment]
db 2MB秒出，
1.05GB堆没了
@4ra1n

**Comment by Gosiu** [comment]
当时描述这个API的时候很模糊，我不清楚这个字符串查的是方法名还是path字符串，实现中的查找目标我没有细看
@4ra1n

**Comment by Gosiu** [comment]
> > @Gosiu 有一点小问题，我这边看看修复下就可以
> > ![image](https://private-user-images.githubusercontent.com/34726933/349764333-b2b52245-48e5-4e1e-bde6-932ec24ff2dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyNzE0NDcsIm5iZiI6MTcyMTI3MTE0NywicGF0aCI6Ii8zNDcyNjkzMy8zNDk3NjQzMzMtYjJiNTIyNDUtNDhlNS00ZTFlLWJkZTYtOTMyZWMyNGZmMmRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDAyNTIyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwZGEyYzkyY2FlZDdhMzJlNWNjNTU5MzQ4N2IyZmY4NDkwN2QyZWUyNmE0ZmQzNzgyNjI2MzA5N2U0OTVjODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yUzwKt793-3erXq35HlfzQKXc8I5Bv6CHsxXxEY-JYQ)
> 
> 此实现在实际使用中存在内存溢出的情况，我想把spring这类操作逐步移到gui。 目前还发现了重建db时，数据不会覆盖的问题，生成时，实际数据会在表中重复 @4ra1n

看堆栈，和映射没有关系

**Comment by 4ra1n** [comment]
嗯 HTTP API 部分，我不想用 SPRING 那一坨，用了轻量的这种，当时写法也是匆忙了一些，大佬有时间可以帮忙改写下！

具体的字符串搜索是搜索 LDC 指令，注解的字符串是没有 LDC 指令的

**Comment by 4ra1n** [comment]
@Gosiu 你可以把你发现的每一个问题，开个新的 issue 来说明的和讨论，一个 issue 包含太多，有点杂哈哈

感谢！

**Comment by Gosiu** [comment]
方便恰个v？我看到你b站主页了

**Comment by 4ra1n** [comment]
@Gosiu 你 B站 私信我，我发你
