### ISSUE TITLE
mac如何使用

### ISSUE THREAD

**Issue by rongyanjuren** [jar-analyzer/jar-analyzer#38]
<img width="474" alt="image" src="https://github.com/user-attachments/assets/97bfebfa-04d8-4886-80f7-834bc029e8dd">，这个是我下载并解压的文件，
<img width="722" alt="image" src="https://github.com/user-attachments/assets/cfae495d-427a-4645-b867-6c5e9cfdd60b">
我下载的这个文件

**Comment by 4ra1n** [comment]
java -jar jar-analyzer-xxx.jar gui 即可启动

推荐 java 8

**Comment by rongyanjuren** [comment]
可以了，谢谢
