### ISSUE TITLE
README笔误

### ISSUE THREAD

**Issue by xcx1r3** [jar-analyzer/jar-analyzer#4]
这段“Zoo.run -> dog.cat 的字节码是 INVOKEVIRTUAL Animal.eat ()V”应该是dog.eat?

**Comment by 4ra1n** [comment]
我验证了下，确实是 `animal.eat` 哈，如图

![image](https://github.com/jar-analyzer/jar-analyzer/assets/34726933/d59167ec-281f-4a5a-ad32-de22141e855a)
