### ISSUE TITLE
能增加分析指定包名开头的所有class文件吗？

### ISSUE THREAD

**Issue by wouijvziqy** [jar-analyzer/jar-analyzer#6]
希望增加这个功能，例如说，分析某个fat jar里，指定包名开头的，例如包名为com.xxx开头的所有class文件，包括jar里面的jar的class文件。因为如果不指定包名，对于大型项目分析所有class文件，耗费时间和内存非常大，并且通常很多三方lib库里的内容不是主要关心的内容。

**Comment by 4ra1n** [comment]
感谢你的简易，确实是一个必要重要的需求
