### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by n2ryx** [jar-analyzer/jar-analyzer#60]
## 描述 | DESC

MacOS 无法打开，（还有8u211双击打开jar，提示jdk21）

## 复现 | REPRODUCE

java -jar jar-analyzer-3.0.jar

## 截图 | SCREENSHOT

<img width="703" alt="截屏2024-08-15 11 58 14" src="https://github.com/user-attachments/assets/c4cf159c-417a-4bb9-a4dc-bc19cfdb9744">

<img width="285" alt="image" src="https://github.com/user-attachments/assets/ea0b5479-18ae-480e-8dcb-40cdeea99833">

## 环境 | ENV

环境信息
- MacOS 14.0
- jar-analyzer-3.0
- zip

**Comment by n2ryx** [comment]
2.24 也打不开😭

**Comment by 4ra1n** [comment]
java -version 看下版本，看下是 8 还是 21

**Comment by 4ra1n** [comment]
尝试用 JAVA 8 的绝对路径启动：

/Lib/.../JVM/.../bin/java -jar jar-analyzer.jar

**Comment by n2ryx** [comment]
`$ java -version
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)
n2ryx@MacBook-Key:~/Security/finger/jar-analyzer-3.0/lib
$ java -jar jar-analyzer-3.0.jar
[*] JAVA 8 LOAD SECURITY MANAGER SUCCESS
[*] LOAD OBJECT INPUT FILTER SUCCESS
     ____.               _____                .__
    |    |____ _______  /  _  \   ____ _____  |  | ___.__.________ ___________
    |    \__  \\_  __ \/  /_\  \ /    \\__  \ |  |<   |  |\___   // __ \_  __ \
/\__|    |/ __ \|  | \/    |    \   |  \/ __ \|  |_\___  | /    /\  ___/|  | \/
\________(____  /__|  \____|__  /___|  (____  /____/ ____|/_____ \\___  >__|
              \/              \/     \/     \/     \/           \/    \/
Jar Analyzer 3.0 @ 4ra1n (https://github.com/4ra1n)
Project Address -> https://github.com/jar-analyzer/jar-analyzer

感谢以下贡献者（按照贡献量排序）
 -> 4ra1n (https://github.com/4ra1n) COMMITS: 626
 -> Gosiu (https://github.com/Gosiu) COMMITS: 11
 -> whwlsfb (https://github.com/whwlsfb) COMMITS: 2

[14:08:04] [INFO] [Version:check:32] safe - java version is higher than 191
[-] UNKNOWN LOG LEVEL USE INFO LEVEL BY DEFAULT
Warning: the font "Times" is not available, so "Lucida Bright" has been substituted, but may have unexpected appearance or behavor. Re-enable the "Times" font to remove this warning.
[14:08:06] [INFO] [ThemeHelper:process:20] setup look and feel success
Usage: <main class> [command] [command options]
  Commands:
    build      build database
      Usage: build [options]
        Options:
          --del-cache
            delete old cache
            Default: false
          --del-exist
            delete old database
            Default: false
          -j, --jar
            jar file/dir

    gui      start jar-analyzer gui
      Usage: gui [options]
        Options:
          -l, --log-level
            set log level (debug|info|warn|error)
          -p, --port
            server port
            Default: 0
          -t, --theme
            use theme name
            (default|metal|win|win-classic|motif|mac|gtk|cross|aqua|nimbus)

`
log
[14:07:41] [WARN] [Version:check:41] please use java 8 version
[14:07:44] [INFO] [ThemeHelper:process:20] setup look and feel success
[14:08:04] [INFO] [Version:check:32] safe - java version is higher than 191
[14:08:06] [INFO] [ThemeHelper:process:20] setup look and feel success

**Comment by 4ra1n** [comment]
这个成功启动了，使用 java -jar jar-analzyer.jar gui 即可启动 GUI 界面

**Comment by n2ryx** [comment]
o了
