### ISSUE TITLE
[BUG] 导出反编译结果功能不正常

### ISSUE THREAD

**Issue by winezer0** [jar-analyzer/jar-analyzer#64]
## 描述 | DESC

导出反编译结果不正常

发现导出的结果就是输入的war包

![image](https://github.com/user-attachments/assets/86840c74-06b1-4f8c-a77f-c692523aa1c6)

![image](https://github.com/user-attachments/assets/7feb4c4b-0ef3-4571-9d29-28082588303b)

## 复现 | REPRODUCE

直接导出即可

## 截图 | SCREENSHOT

![image](https://github.com/user-attachments/assets/9aec25bf-9e1b-4acb-96f3-271981cb8016)
## 环境 | ENV

![image](https://github.com/user-attachments/assets/52b2bb8f-e1fc-4e32-8dfa-a2d7b30d2c0b)

环境信息
- windows 10  jar-analyzer-3.0-windows-full

**Comment by 4ra1n** [comment]
查看下war里面是否是java文件，另外尝试把war后缀改成jar再试试

之后我看看支持下war文件
