### ISSUE TITLE
[BUG]对于一些无法用360zip打开的jar包，本程序也无法加载代码

### ISSUE THREAD

**Issue by winezer0** [jar-analyzer/jar-analyzer#66]
## 描述 | DESC

对于一些无法用360zip打开的jar包，本程序也无法加载代码

用bandzip重新解压，压缩，改后缀jar后可以加载

## 复现 | REPRODUCE

请考虑添加联系方式

**Comment by 4ra1n** [comment]
你可以加我V联系下：X1l1a2lub1JhaW5f

**Comment by winezer0** [comment]
这个没加密吧，搜不到哦

**Comment by winezer0** [comment]
4ra1n 昵称搜不到，还有其他昵称吗

**Comment by 4ra1n** [comment]
那你发你联系方式到 emyiqing@gmail.com 我加你

**Comment by winezer0** [comment]
null_user_name VX
