### ISSUE TITLE
[BUG]加载springboot的jar包点击提示需要依赖

### ISSUE THREAD

**Issue by winezer0** [jar-analyzer/jar-analyzer#67]
## 描述 | DESC

加载springboot的jar包，显示了控制器，但是点击提示需要依赖

## 复现 | REPRODUCE
一个平平无奇的jar包

## 截图 | SCREENSHOT
![image](https://github.com/user-attachments/assets/dd5c6b04-ed49-4cd3-a8dd-0f2fb5d5ec57)

![image](https://github.com/user-attachments/assets/bd7de6aa-0406-4115-b236-dd08cc81c61f)

**Comment by 4ra1n** [comment]
是否勾选了这个

![image](https://github.com/user-attachments/assets/42eb458d-5f4b-4e8a-ae6d-d024dbe00a0b)

**Comment by winezer0** [comment]
![image](https://github.com/user-attachments/assets/fc4d5018-1291-4cf2-b63b-1ee09aa35860)

**Comment by 4ra1n** [comment]
需要勾选，springboot的依赖是内嵌jar，普通jar不是

**Comment by 4ra1n** [comment]
auto find rt.jar 只是找，不会生效，勾选 add rt.jar 生效

**Comment by winezer0** [comment]
好的，感谢，

**Comment by winezer0** [comment]
rt.jar  这个不添加可以吗，我都勾选了，加载有点慢，没找到介绍内容

**Comment by 4ra1n** [comment]
add rt.jar 一般不需要，这个场景是你需要分析 JDK 内部的某些类和调用，好处是你分析过程中的任何调用都不会显示 no dependency

**Comment by winezer0** [comment]
好的，
