### ISSUE TITLE
[BUG] 在使用lambda/Streamd/Runnable等特性时丢失分析结果

### ISSUE THREAD

**Issue by wouijvziqy** [jar-analyzer/jar-analyzer#8]
在使用lambda、Streamd、Runnable等特性时，会丢失调用关系，也许可以通过使用visitInvokeDynamicInsn解决
例如：
@Override
public void visitInvokeDynamicInsn(String name, String descriptor, Handle bootstrapMethodHandle, Object... bootstrapMethodArguments) {
    for (Object bsmArg : bootstrapMethodArguments) {
        if (bsmArg instanceof Handle) {
            Handle handle = (Handle) bsmArg;
            calledMethods.add(new MethodReference.Handle(new ClassReference.Handle(handle.getOwner()), handle.getName(), handle.getDesc()));
        }
    }
    super.visitInvokeDynamicInsn(name, descriptor, bootstrapMethodHandle, bootstrapMethodArguments);
}

**Comment by 4ra1n** [comment]
我发现显示某个类已有方法的代码部分忽略了`lambda`和`access$`等方法，这里也需要解决
```java
    public static void refreshAllMethods(String className) {
        ArrayList<MethodResult> results = MainForm.getEngine().getMethodsByClass(className);
        DefaultListModel<MethodResult> methodsList = new DefaultListModel<>();
        for (MethodResult result : results) {
            // 这里
            if (result.getMethodName().startsWith("lambda$")) {
                continue;
            }
            if (result.getMethodName().startsWith("access$")) {
                continue;
            }
            if (result.getMethodName().equals("<clinit>")) {
                continue;
            }
            methodsList.addElement(result);
        }
        MainForm.getInstance().getAllMethodList().setCellRenderer(new AllMethodsRender());
        MainForm.getInstance().getAllMethodList().setModel(methodsList);
        MainForm.getInstance().getAllMethodList().repaint();
        MainForm.getInstance().getAllMethodList().revalidate();
    }
```
